### ISSUE TITLE
ConstructionMethod.SORTING on windows prevents renaming .spi file

### ISSUE THREAD

**Issue by bckfnn** [spotify/sparkey-java#34]
Thanks for adding the sorting hash algorithm, it is a great for loading 500M entries.

With version 2.3.0, the sorting hash writer and a Windows PC, this small example

```
    public static void main(String[] args) throws IOException {
        final SparkeyWriter writer = Sparkey.createNew(new File("test-store.spi"), CompressionType.NONE, 0);

        writer.put("foo", "bar");

        writer.flush();
        writer.setConstructionMethod(SparkeyWriter.ConstructionMethod.SORTING);
        writer.setHashType(HashType.HASH_64_BITS);
        writer.writeHash();
        writer.close();
    }
```

fails with 

```
Exception in thread "main" java.io.IOException: Could not rename C:\inno\kvtest\test-store.spi-tmp9431a3cc-4f48-453b-bcab-bb67f10ffa54 to test-store.spi
	at com.spotify.sparkey.SingleThreadedSparkeyWriter.writeHash(SingleThreadedSparkeyWriter.java:106)
	at dk.innovasion.TestCleaner.main(TestCleaner.java:21)
```

I guess the cause is the scheduled call to ByteBufferCleaner.cleanMapping(chunk); which is executed a long time after the attempt to rename the .spi file.

**Comment by spkrka** [comment]
Thanks for the report - I will try to investigate/fix it at some point.

I don't think it's directly related to the sorting itself, but more related to a change in how it opens the file of writing.
With the old creation behaviour it wrote everything to heap first and then simply flushed that to disk using FileOutputStream, but now using sorting it memory maps the spi file instead and writes via that.

I suppose this might only be a problem in OS's which don't permit renaming files that are being used.
(Linux in generally doesn't care)

Potential fixes include:
* Change the internals to explicitly clean up the mmapping before renaming the file
* Write the data using FileOutputStream instead (slightly trickier since it uses random access now, but doable)

**Comment by spkrka** [comment]
Can you try this version and see if it helps you? I am not running on windows myself

**Comment by bckfnn** [comment]
The fix is perfect. Thank you for the fast solution and for sparkey.
